# sample-workflow-windows-latest
# docs are in the repo

name: Code Analysis on-push-verification windows-latest
on: push

jobs:
  sample:
    name: .NET Code Analysis runner

    # .NET Code Analysis runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: windows-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v2

    # Ensure a compatible version of dotnet is installed.
    # The [Microsoft Security DevOps CLI](https://aka.ms/msdo-nuget) is built with net6.0
    # A version greater than or equal to net6.0 of dotnet must be installed on the agent in order to run this action.
    # GitHub hosted runners already have a compatible version of dotnet installed and this step may be skipped.
    
    # For self-hosted runners, ensure dotnet version 3.1.201 or later is installed by including this action:
    # - uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: '6.0.x'

    # Run NuGet restore
    - name: Run NuGet restore
      run: dotnet restore .\sample\ClassLibrary1.sln

    # Run .NET Code Analysis
    - name: Run .NET Code Analysis
      uses: ./
      id: code-analysis
      with:
        project: .\sample\ClassLibrary1.sln
        build-breaking: false
        all-categories: all

    # Upload the analysis results file
    - name: Upload analysis results
      uses: actions/upload-artifact@v2
      with:
        name: analysis_results.sarif
        path: ${{ steps.code-analysis.outputs.sarifFile }}
